/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const EnrollmentApplication = IDL.Record({
  'previousSchool' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'submissionTimestamp' : Time,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'gradeLevel' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const StudentQuestion = IDL.Record({
  'question' : IDL.Text,
  'submissionTimestamp' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getApplications' : IDL.Func([], [IDL.Vec(EnrollmentApplication)], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(StudentQuestion)], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitQuestion' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const EnrollmentApplication = IDL.Record({
    'previousSchool' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'submissionTimestamp' : Time,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'gradeLevel' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const StudentQuestion = IDL.Record({
    'question' : IDL.Text,
    'submissionTimestamp' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getApplications' : IDL.Func(
        [],
        [IDL.Vec(EnrollmentApplication)],
        ['query'],
      ),
    'getQuestions' : IDL.Func([], [IDL.Vec(StudentQuestion)], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };